---
name: Build Claat Workshops and push to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
    steps:
      - name: Checkout Website App
        uses: actions/checkout@v4
        with:
          repository: sjg/amr
          ref: web-source
      
      - name: Checkout Workshop Files
        uses: actions/checkout@v4
        with:
          repository: sjg/amr
          ref: main
          path: codelab-src
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 10.15
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with: 
          files: | 
            **.md
      
      - name:  Download Latest Version of CLAAT
        id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_path: googlecodelabs/tools
      
      - name: Download 
        run: |
          ls ${{ github.workspace }}
          wget -O download.json ${{ steps.fetch-latest-release.outputs.assets_url }}

      - name: Extract version from download-link.json
        uses: sergeysova/jq-action@v2
        id: download-link
        with:
          cmd: jq '.[] | select(.name =="claat-linux-amd64") | .browser_download_url' download.json -r 

      - name: Build All Claat Workshops
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: |
          wget ${{ steps.download-link.outputs.value }}
          mv claat-linux-amd64 ./claat
          chmod +x ./claat
          ls -lha ${{ github.workspace }}
          
          mkdir ${{ github.workspace }}/codelabs

          # Build Changed Codelabs
          # for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
          #   if [ $file != "README.md" ]
          #   then
          #     echo "Building: $file"
          #     ./claat export --prefix "https://sjg.github.io/amr/elements" -o ${{ github.workspace }}/codelabs $file
          #   fi
          # done

          find ./codelab-src -name '*.md' > /tmp/mdFiles.dat

          while read FILE
          do
          	FILENAME=$(basename $FILE)
          	if [ $FILENAME != "README.md" ]
          	then
              echo "Building:- $FILE"
          		 ./claat export --prefix "https://sjg.github.io/amr" -f codelab-template.html -o ${{ github.workspace }}/codelabs $FILE
          	fi
          done <  /tmp/mdFiles.dat
          
          ls -lha ${{ github.workspace }}/codelabs
      
      - name: Build Site
        run: |
          npm i
          gulp dist --codelabs-dir=./codelabs --baseUrl="https://sjg.github.io/amr" --GA_UA="UA-999999999-9"
          
          # Fix new file structure in the claat tool cli - added claat-public folder 
          mkdir ./dist/claat-public
          cp -R ./dist/elements/codelab-elements/. ./dist/claat-public/.
          cp -R ./dist/elements/. ./dist/claat-public/.

      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          exclude_assets: .github,.gitignore
      
      - name: List files in the repository
        run: |
          ls -lha ${{ github.workspace }}/dist
          ls -lha ${{ github.workspace }}/codelabs
          ls -lha ${{ github.workspace }}/
