name: Build Claat Website and push to GitHub Pages

on:
  push:
    branches: [ "web-source" ]
  #pull_request:
    #branches: [ "main" ]

permissions: write-all

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout Website App
      uses: actions/checkout@v4
      with:
        repository: sjg/amr
        ref: web-source

    - name: Checkout Workshop Files
      uses: actions/checkout@v4
      with:
        repository: sjg/amr
        ref: main
        path: codelab-src
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 10.15

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1' 
     
    - name: Build Site
      run: | 
        npm i
        mkdir ${{ github.workspace }}/codelabs
        gulp dist --codelabs-dir=./codelabs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        exclude_assets: '.github,.gitignore'

    # - name: List files in the repository
    #   run: |
    #     ls ${{ github.workspace }}/dist
