name: Build Claat Website and push to GitHub Pages

on:
  push:
    branches: [ "web-source" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout Website App
      uses: actions/checkout@v4
      with:
        repository: sjg/amr
        ref: web-source

    - name: Checkout Workshop Files
      uses: actions/checkout@v4
      with:
        repository: sjg/amr
        ref: main
        path: codelab-src
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Setup Node and Python
      uses: actions/setup-python@v5
      with:
        python-version: '2.7.18' 
     
    - name: Build Site
      run: | 
        npm i
        gulp dist --codelabs-dir=./codelabs

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}/dist
